version: 0.0
os: linux
files:
 - source: /page_turn_decipher
   destination: /home/ec2-user/page-turn-decipher
 - source: requirements.txt
   destination: /home/ec2-user/page-turn-decipher
permissions:
  - object: /home/ec2-user/page-turn-decipher/app.py
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/page-turn-decipher/requirements.txt
    owner: ec2-user
    mode: 644
    type:
      - file
hooks:
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 300
     runas: root
   - location: scripts/start_server
     timeout: 300
     runas: root
  ApplicationStop:
   - location: scripts/stop_server
     timeout: 300
     runas: root